import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import { mockMapData } from './map-fixtures'

test.beforeEach(async ({ page }) => {
  await mockMapData(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?person=li-bai&category=literature')
  await expect(page.locator('.map-person-marker.selected')).toBeVisible({ timeout: 20_000 })
})

test('the canvas owns the screen while filters and tools expand on demand', async ({ page }) => {
  const dimensions = await page.locator('.map-canvas').evaluate((element) => ({ height: element.clientHeight, viewport: window.innerHeight }))
  expect(dimensions.height / dimensions.viewport).toBeGreaterThan(0.9)
  await expect(page.getByRole('region', { name: '时代与领域' })).toBeHidden()
  await expect(page.getByRole('region', { name: '地图工具', exact: true })).toBeHidden()
  const filters = page.getByRole('button', { name: '展开时代与领域' })
  await filters.click()
  const drawer = page.getByRole('region', { name: '时代与领域' })
  await expect(drawer).toBeVisible()
  await expect(drawer.getByRole('button', { name: /^文学/ })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.locator('.map-canvas').evaluate((element) => element.clientHeight)).toBe(dimensions.height)
  await drawer.getByRole('button', { name: '收起时代与领域' }).click()
  await expect(filters).toBeFocused()
  await page.getByRole('button', { name: '展开地图工具' }).click()
  const tools = page.getByRole('region', { name: '地图工具', exact: true })
  await expect(tools.getByRole('button', { name: '山河', exact: true })).toBeVisible()
  await tools.getByRole('button', { name: '山河', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '展开地图工具' })).toBeFocused()
  await expect(page.locator('.history-map')).toHaveClass(/map-theme-landscape/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
})

test('focus mode preserves camera, selection, and expanded panel state', async ({ page }, testInfo) => {
  const panel = page.locator('.person-panel')
  if (testInfo.project.name === 'mobile-chromium') await page.getByRole('button', { name: '展开人物详情' }).click()
  await page.getByRole('button', { name: '展开时代与领域' }).click()
  const url = page.url()
  const scrollTop = await panel.evaluate((element) => { element.scrollTop = 100; return element.scrollTop })
  const canvas = await page.locator('.maplibregl-canvas').elementHandle()
  const zoom = await page.locator('.history-map').getAttribute('data-zoom')
  await page.getByRole('button', { name: '专注地图', exact: true }).click()
  await expect(panel).toBeHidden()
  await expect(page.getByRole('region', { name: '时代与领域' })).toBeHidden()
  await expect(page.locator('.history-map')).toHaveAttribute('data-zoom', zoom!)
  expect(await canvas!.evaluate((element) => element.isConnected)).toBe(true)
  await expect(page).toHaveURL(url)
  const result = await new AxeBuilder({ page }).analyze()
  expect(result.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact ?? ''))).toEqual([])
  await page.keyboard.press('Control+K')
  await expect(page.getByRole('dialog', { name: '名人名录' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '退出专注地图' })).toBeFocused()
  await expect(panel).toBeHidden()
  await page.getByRole('button', { name: '展开地图工具' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '展开地图工具' })).toBeFocused()
  await expect(panel).toBeHidden()
  await page.locator('.maplibregl-canvas').click({ position: { x: 25, y: 65 } })
  await expect(page.getByRole('region', { name: '探索此地' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('region', { name: '探索此地' })).toBeHidden()
  await expect(panel).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(panel).toBeVisible()
  expect(await panel.evaluate((element) => element.scrollTop)).toBe(scrollTop)
  if (testInfo.project.name === 'mobile-chromium') await expect(panel).toHaveClass(/expanded/)
  await expect(page.getByRole('region', { name: '时代与领域' })).toBeVisible()
  await expect(page.getByRole('button', { name: '专注地图', exact: true })).toBeFocused()
})

test('controls remain reachable on narrow screens with expanded or hidden details', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile-chromium', 'narrow mobile layout assertion')
  await page.setViewportSize({ width: 320, height: 568 })
  await page.getByRole('button', { name: '展开人物详情' }).click()
  await page.getByRole('button', { name: '展开地图工具' }).click()
  const tools = page.getByRole('region', { name: '地图工具', exact: true })
  const header = await page.locator('.topbar').boundingBox()
  const toolbox = await tools.boundingBox()
  expect(toolbox!.y).toBeGreaterThanOrEqual(header!.y + header!.height)
  expect(toolbox!.x + toolbox!.width).toBeLessThanOrEqual(320)
  await tools.getByRole('button', { name: '时代全景' }).click()
  await page.getByRole('button', { name: '专注地图', exact: true }).click()
  const marker = page.locator('.map-person-marker:not(.selected)').first()
  await marker.focus()
  const preview = page.locator('.map-person-preview')
  await expect(preview).toBeVisible()
  const box = await preview.boundingBox()
  expect(box!.y).toBeGreaterThanOrEqual(header!.y + header!.height)
  expect(box!.y + box!.height).toBeLessThanOrEqual(568)
  await preview.click()
  await expect(page.locator('.person-panel')).toBeHidden()
  await page.getByRole('button', { name: /打开人物卷轴/ }).click()
  await expect(page.locator('.person-panel')).toHaveClass(/expanded/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
})
