import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import { journeys } from './data/journeys'
import { personById } from './data/people'
import { SAVED_PEOPLE_KEY } from './lib/savedPeople'

vi.mock('./components/HistoryMap', () => ({
  default: ({ people, selected, onSelect }: { people: Array<{ id: string; name: string }>; selected: { id: string; name: string }; onSelect: (person: { id: string; name: string }) => void }) => (
    <section aria-label="测试人物地图" data-selected={selected.id}>
      {people.map((person) => <button type="button" key={person.id} onClick={() => onSelect(person)}>{person.name}</button>)}
    </section>
  ),
}))

describe('PeopleCloud application', () => {
  beforeEach(() => {
    window.history.replaceState({}, '', '/')
    window.localStorage.clear()
  })
  afterEach(() => {
    cleanup()
    vi.restoreAllMocks()
  })

  it('enters the experience and keeps period, person and URL synchronized', async () => {
    const user = userEvent.setup()
    render(<App />)
    expect(screen.getByRole('heading', { name: /群星落人间/ })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: '进入星图' }))
    expect(await screen.findByRole('button', { name: /唐，618—907/ })).toHaveAttribute('aria-current', 'true')
    expect(screen.getByRole('complementary', { name: /人物详情/ })).toHaveAttribute('data-person-id', 'tang-taizong')
    expect(window.location.search).toContain('period=tang')

    await user.click(screen.getByRole('button', { name: /宋，960—1279/ }))
    expect(screen.getByRole('complementary', { name: /人物详情/ })).toHaveAttribute('data-person-id', 'su-shi')
    expect(window.location.search).toContain('person=su-shi')
  })

  it('filters by an available field and disables absent fields', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: '进入星图' }))
    const filters = screen.getByRole('region', { name: '测试人物地图' }).parentElement!
    await user.click(screen.getByRole('button', { name: /秦，前221—前206/ }))
    const medicine = within(filters).getByRole('button', { name: /医学/ })
    expect(medicine).toBeDisabled()
    await user.click(screen.getByRole('button', { name: /唐，618—907/ }))
    await user.click(within(filters).getByRole('button', { name: /文学/ }))
    expect(screen.getByText(/文学 · \d+ 位人物/)).toBeInTheDocument()
  })

  it('normalizes an unavailable URL category so the selected person remains visible', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?period=qin&category=medicine')
    render(<App />)
    const map = await screen.findByRole('region', { name: '测试人物地图' })
    expect(map).toHaveAttribute('data-selected', 'qin-shihuang')
    expect(within(map).getByRole('button', { name: '秦始皇' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /^全部 / })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('button', { name: /^医学/ })).toBeDisabled()
    await user.click(screen.getByRole('button', { name: '下一位人物' }))
    expect(window.location.search).not.toContain('category=')
    const selectedId = screen.getByRole('complementary').getAttribute('data-person-id')
    expect(map).toHaveAttribute('data-selected', selectedId)
    expect(within(map).getByRole('button', { name: personById.get(selectedId!)!.name })).toBeInTheDocument()
  })

  it('searches the full directory and selects a cross-period person', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: '进入星图' }))
    await user.click(screen.getByRole('button', { name: /名录/ }))
    const dialog = screen.getByRole('dialog', { name: '名人名录' })
    const search = within(dialog).getByRole('searchbox', { name: '搜索人物' })
    await user.type(search, '郭守敬')
    expect(within(dialog).getByRole('status')).toHaveTextContent('找到 1 位人物')
    await user.click(within(dialog).getByRole('button', { name: /郭守敬/ }))
    expect(screen.queryByRole('dialog', { name: '名人名录' })).not.toBeInTheDocument()
    expect(screen.getByRole('complementary', { name: /郭守敬人物详情/ })).toBeInTheDocument()
    expect(window.location.search).toContain('period=yuan')
  })

  it('enters from the featured card and navigates a remembered person trail', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: '从李白开始探索' }))
    expect(screen.getByRole('complementary', { name: /李白人物详情/ })).toBeInTheDocument()
    expect(window.location.search).toContain('person=li-bai')

    await user.click(screen.getByRole('button', { name: '下一位人物' }))
    expect(screen.queryByRole('complementary', { name: /李白人物详情/ })).not.toBeInTheDocument()
    const trail = screen.getByRole('heading', { name: /你的星图足迹/ }).parentElement!
    await user.click(within(trail).getByRole('button', { name: /李白/ }))
    expect(screen.getByRole('complementary', { name: /李白人物详情/ })).toBeInTheDocument()
  })

  it('compares two people and can continue from the comparison', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: '进入星图' }))
    await user.click(screen.getByRole('button', { name: '人物对照' }))
    const dialog = screen.getByRole('dialog', { name: '人物对照' })
    const search = within(dialog).getByRole('searchbox', { name: '搜索对照人物' })
    await user.type(search, '郭守敬')
    await user.click(within(dialog).getByRole('button', { name: /郭守敬/ }))
    expect(within(dialog).getByRole('heading', { name: '郭守敬' })).toBeInTheDocument()
    await user.click(within(dialog).getByRole('button', { name: '在星图中查看 郭守敬' }))
    expect(screen.getByRole('complementary', { name: /郭守敬人物详情/ })).toBeInTheDocument()
    expect(window.location.search).toContain('period=yuan')
  })

  it('closes dialogs with Escape and restores focus', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: '进入星图' }))
    const help = screen.getByRole('button', { name: '查看使用与数据说明' })
    fireEvent.click(help)
    expect(screen.getByRole('dialog', { name: '关于人间星图' })).toBeInTheDocument()
    fireEvent.keyDown(document, { key: 'Escape' })
    await waitFor(() => expect(screen.queryByRole('dialog', { name: '关于人间星图' })).not.toBeInTheDocument())
    await waitFor(() => expect(help).toHaveFocus())
  })

  it('saves a person, searches the collection, reloads it, and removes it from the directory', async () => {
    const user = userEvent.setup()
    const { unmount } = render(<App />)
    await user.click(screen.getByRole('button', { name: '从李白开始探索' }))
    const save = screen.getByRole('button', { name: '收藏李白' })
    expect(save).toHaveAttribute('aria-pressed', 'false')
    await user.click(save)
    expect(screen.getByRole('button', { name: '取消收藏李白' })).toHaveAttribute('aria-pressed', 'true')
    expect(JSON.parse(window.localStorage.getItem(SAVED_PEOPLE_KEY)!)).toEqual(['li-bai'])
    await user.click(screen.getByRole('button', { name: '打开名人名录' }))
    let dialog = screen.getByRole('dialog', { name: '名人名录' })
    await user.click(within(dialog).getByRole('button', { name: /我的收藏/ }))
    expect(within(dialog).getByRole('status')).toHaveTextContent('找到 1 位人物')
    const search = within(dialog).getByRole('searchbox', { name: '搜索人物' })
    await user.type(search, '诗仙')
    expect(within(dialog).getByRole('status')).toHaveTextContent('找到 1 位人物')
    await user.clear(search)
    await user.type(search, '郭守敬')
    expect(within(dialog).getByRole('heading', { name: '没有找到匹配的收藏' })).toBeInTheDocument()
    await user.click(within(dialog).getByRole('button', { name: '清除全部筛选' }))
    await user.click(within(dialog).getByRole('button', { name: /李白/ }))
    unmount()

    render(<App />)
    expect(screen.getByRole('button', { name: '取消收藏李白' })).toHaveAttribute('aria-pressed', 'true')
    await user.click(screen.getByRole('button', { name: '打开名人名录' }))
    dialog = screen.getByRole('dialog', { name: '名人名录' })
    await user.click(within(dialog).getByRole('button', { name: /我的收藏/ }))
    await user.click(within(dialog).getByRole('button', { name: '取消收藏' }))
    expect(within(dialog).getByRole('heading', { name: '还没有收藏人物' })).toBeInTheDocument()
    expect(within(dialog).getByRole('searchbox', { name: '搜索人物' })).toHaveFocus()
    expect(window.localStorage.getItem(SAVED_PEOPLE_KEY)).toBe('[]')
    await user.keyboard('{Escape}')
    expect(screen.getByRole('button', { name: '收藏李白' })).toHaveAttribute('aria-pressed', 'false')
  }, 15_000)

  it('can save from directory cards and return from an empty collection', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai')
    render(<App />)
    await user.click(screen.getByRole('button', { name: '打开名人名录' }))
    const dialog = screen.getByRole('dialog', { name: '名人名录' })
    await user.click(within(dialog).getByRole('button', { name: /我的收藏/ }))
    await user.click(within(dialog).getByRole('button', { name: '浏览全部人物' }))
    expect(within(dialog).getByRole('button', { name: '全部人物' })).toHaveAttribute('aria-pressed', 'true')
    await user.type(within(dialog).getByRole('searchbox', { name: '搜索人物' }), '诗仙')
    const save = within(dialog).getByRole('button', { name: '收藏此人' })
    await user.click(save)
    expect(save).toHaveFocus()
    expect(save).toHaveAttribute('aria-pressed', 'true')
    await user.keyboard('{Escape}')
    await user.click(screen.getByRole('button', { name: '取消收藏李白' }))
    expect(screen.getByRole('button', { name: '收藏李白' })).toHaveAttribute('aria-pressed', 'false')
    expect(window.localStorage.getItem(SAVED_PEOPLE_KEY)).toBe('[]')
  }, 15_000)

  it('reports storage failures and keeps the last successfully saved state until retry', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai')
    window.localStorage.setItem(SAVED_PEOPLE_KEY, '["li-bai"]')
    render(<App />)
    const write = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('Full', 'QuotaExceededError') })
    await user.click(screen.getByRole('button', { name: '取消收藏李白' }))
    expect(screen.getByRole('alert')).toHaveTextContent('收藏更改未保存')
    expect(screen.getByRole('button', { name: '取消收藏李白' })).toHaveAttribute('aria-pressed', 'true')
    await user.click(screen.getByRole('button', { name: '打开名人名录' }))
    expect(within(screen.getByRole('dialog')).getByRole('alert')).toHaveTextContent('收藏更改未保存')
    await user.keyboard('{Escape}')
    write.mockRestore()
    await user.click(screen.getByRole('button', { name: '取消收藏李白' }))
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '收藏李白' })).toHaveAttribute('aria-pressed', 'false')
  })

  it('shows unavailable or malformed storage explicitly without blocking discovery', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai')
    window.localStorage.setItem(SAVED_PEOPLE_KEY, '{bad data')
    render(<App />)
    expect(screen.getByRole('alert')).toHaveTextContent('收藏记录无法解析')
    await user.click(screen.getByRole('button', { name: '收藏李白' }))
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(window.localStorage.getItem(SAVED_PEOPLE_KEY)).toBe('["li-bai"]')
  })

  it('synchronizes saved people when another tab changes or clears storage', async () => {
    window.history.replaceState({}, '', '/?person=li-bai')
    render(<App />)
    window.localStorage.setItem(SAVED_PEOPLE_KEY, '["li-bai","missing-id"]')
    fireEvent(window, new StorageEvent('storage', { key: SAVED_PEOPLE_KEY }))
    expect(screen.getByRole('button', { name: '取消收藏李白' })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('alert')).toHaveTextContent('部分收藏记录已失效')
    expect(screen.queryByText('收藏已与此浏览器同步。')).not.toBeInTheDocument()
    window.localStorage.clear()
    fireEvent(window, new StorageEvent('storage', { key: null }))
    expect(screen.getByRole('button', { name: '收藏李白' })).toHaveAttribute('aria-pressed', 'false')
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
  })

  it('curates three distinct reading sequences using real, unique corpus people', () => {
    expect(journeys).toHaveLength(3)
    expect(new Set(journeys.map((journey) => journey.id)).size).toBe(3)
    for (const journey of journeys) {
      expect(journey.introduction.length).toBeGreaterThan(30)
      expect(journey.stops.length).toBeGreaterThanOrEqual(3)
      expect(new Set(journey.stops.map((stop) => stop.personId)).size).toBe(journey.stops.length)
      for (const stop of journey.stops) {
        expect(personById.has(stop.personId)).toBe(true)
        expect(stop.note.length).toBeGreaterThan(20)
      }
    }
  })

  it('starts a journey, navigates both ways and preserves the expanded mobile panel', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai')
    render(<App />)
    await user.click(screen.getByRole('button', { name: '展开人物详情' }))
    await user.click(screen.getByRole('button', { name: '打开主题漫游' }))
    const dialog = screen.getByRole('dialog', { name: '主题漫游' })
    expect(within(dialog).getByText(/非历史行旅路线/)).toBeInTheDocument()
    await user.click(within(dialog).getByRole('button', { name: '开始漫游：诗里见大唐' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    const journey = screen.getByRole('region', { name: '诗里见大唐' })
    expect(within(journey).getByRole('status')).toHaveTextContent('第 1 / 4 站 · 李白')
    expect(screen.getByRole('button', { name: '漫游上一站' })).toBeDisabled()
    await user.click(screen.getByRole('button', { name: '漫游下一站' }))
    expect(screen.getByRole('complementary', { name: '王维人物详情' })).toHaveClass('expanded')
    expect(screen.getByRole('button', { name: '漫游下一站' })).toHaveFocus()
    expect(window.location.search).toContain('person=wang-wei')
    expect(within(journey).getByRole('status')).toHaveTextContent('第 2 / 4 站 · 王维')
    await user.click(screen.getByRole('button', { name: '漫游上一站' }))
    expect(screen.getByRole('complementary', { name: '李白人物详情' })).toHaveClass('expanded')
    await user.click(screen.getByRole('button', { name: '结束主题漫游' }))
    expect(screen.queryByRole('region', { name: '诗里见大唐' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '下一位人物' })).toBeInTheDocument()
  })

  it('can begin at any stop, cross periods and reach the final stop without wrapping', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai&category=literature')
    render(<App />)
    await user.click(screen.getByRole('button', { name: '打开主题漫游' }))
    let dialog = screen.getByRole('dialog', { name: '主题漫游' })
    await user.click(within(dialog).getByRole('button', { name: /仰观与求证/ }))
    await user.click(within(dialog).getByRole('button', { name: '从第 2 站 祖冲之 开始' }))
    expect(window.location.search).toContain('period=southern-northern')
    expect(window.location.search).not.toContain('category=')
    await user.click(screen.getByRole('button', { name: '漫游下一站' }))
    expect(window.location.search).toContain('period=song')
    await user.click(screen.getByRole('button', { name: '漫游下一站' }))
    expect(window.location.search).toContain('person=guo-shoujing')
    expect(screen.getByRole('button', { name: '漫游下一站' })).toBeDisabled()
    expect(within(screen.getByRole('region', { name: '仰观与求证' })).getByRole('status')).toHaveTextContent('已到终站')
    const contents = screen.getByRole('button', { name: '查看漫游目录' })
    await user.click(contents)
    dialog = screen.getByRole('dialog', { name: '主题漫游' })
    expect(within(dialog).getByRole('button', { name: /仰观与求证/, pressed: true })).toHaveAttribute('aria-pressed', 'true')
    await user.keyboard('{Escape}')
    await waitFor(() => expect(contents).toHaveFocus())
    await user.click(contents)
    await user.click(screen.getByRole('button', { name: '从第 1 站 张衡 开始' }))
    expect(window.location.search).toContain('period=han')
  })

  it('updates the journey when selecting a member and exits for an unrelated person', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai')
    render(<App />)
    await user.click(screen.getByRole('button', { name: '打开主题漫游' }))
    await user.click(screen.getByRole('button', { name: '开始漫游：诗里见大唐' }))
    await user.click(within(screen.getByRole('region', { name: '测试人物地图' })).getByRole('button', { name: '杜甫' }))
    expect(within(screen.getByRole('region', { name: '诗里见大唐' })).getByRole('status')).toHaveTextContent('第 3 / 4 站 · 杜甫')
    await user.click(screen.getByRole('button', { name: '打开名人名录' }))
    const dialog = screen.getByRole('dialog', { name: '名人名录' })
    await user.type(within(dialog).getByRole('searchbox', { name: '搜索人物' }), '郭守敬')
    await user.click(within(dialog).getByRole('button', { name: /郭守敬/ }))
    expect(screen.queryByRole('region', { name: '诗里见大唐' })).not.toBeInTheDocument()
    expect(screen.getByRole('complementary', { name: '郭守敬人物详情' })).toBeInTheDocument()
  })

  it.each(['period', 'category', 'history'] as const)('ends a journey when changing %s', async (change) => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai')
    render(<App />)
    await user.click(screen.getByRole('button', { name: '打开主题漫游' }))
    await user.click(screen.getByRole('button', { name: '开始漫游：诗里见大唐' }))
    if (change === 'period') await user.click(screen.getByRole('button', { name: /宋，960—1279/ }))
    if (change === 'category') {
      const workspace = screen.getByRole('region', { name: '测试人物地图' }).parentElement!
      await user.click(within(workspace).getByRole('button', { name: /^文学/ }))
    }
    if (change === 'history') {
      window.history.replaceState({}, '', '/?person=su-shi')
      fireEvent.popState(window)
    }
    expect(screen.queryByRole('region', { name: '诗里见大唐' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '下一位人物' })).toBeInTheDocument()
  })

  it('leaves a journey when continuing to an unrelated comparison person and restores focus', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai')
    render(<App />)
    await user.click(screen.getByRole('button', { name: '打开主题漫游' }))
    await user.click(screen.getByRole('button', { name: '开始漫游：诗里见大唐' }))
    const compare = screen.getByRole('button', { name: '人物对照' })
    await user.click(compare)
    const dialog = screen.getByRole('dialog', { name: '人物对照' })
    await user.type(within(dialog).getByRole('searchbox', { name: '搜索对照人物' }), '郭守敬')
    await user.click(within(dialog).getByRole('button', { name: /郭守敬/ }))
    await user.click(within(dialog).getByRole('button', { name: '在星图中查看 郭守敬' }))
    expect(screen.queryByRole('region', { name: '诗里见大唐' })).not.toBeInTheDocument()
    expect(screen.getByRole('complementary', { name: '郭守敬人物详情' })).toBeInTheDocument()
    await waitFor(() => expect(compare).toHaveFocus())
  })

  it('restores journey trigger focus on Escape and does not stack shortcut dialogs', async () => {
    const user = userEvent.setup()
    window.history.replaceState({}, '', '/?person=li-bai')
    render(<App />)
    const trigger = screen.getByRole('button', { name: '打开主题漫游' })
    await user.click(trigger)
    fireEvent.keyDown(window, { key: 'k', ctrlKey: true })
    expect(screen.getAllByRole('dialog')).toHaveLength(1)
    expect(screen.queryByRole('dialog', { name: '名人名录' })).not.toBeInTheDocument()
    await user.keyboard('{Escape}')
    await waitFor(() => expect(trigger).toHaveFocus())
    await user.click(trigger)
    await user.click(screen.getByRole('button', { name: /如何安顿此心/ }))
    await user.click(screen.getByRole('button', { name: '开始漫游：如何安顿此心' }))
    expect(screen.getByRole('complementary', { name: '孔子人物详情' })).toBeInTheDocument()
  })
})
